### ISSUE TITLE
[Task] The Y Axis should be OP amount

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/impact-calculator#32]
@swellander  was prescient on this one.

Jonas says

> The Y axis on the chart could be OP amount. Just assume for now that the total OP amount is 10m ([here](https://www.figma.com/file/5q7tNWHSaC7jetMp5UNdd1/Buidl-Guidl-Feedback?type=whiteboard&node-id=1-3&t=Gz2VAc87B5vFitug-4))

Each project's position on the graph equates to their share of that 10m. In addition to changing the way we display the Y axis we will need to adjust the impact API to return the projects percentage of 10m tokens in stead of it's rank.

**Comment by swellander** [comment]
I can take this one
