### ISSUE TITLE
[Task] Weird cutoff of edges on Impact Vector selection

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/impact-calculator#33]
There’s a weird cutoff of edges when viewing on a big screen [here](https://www.figma.com/file/5q7tNWHSaC7jetMp5UNdd1/Buidl-Guidl-Feedback?type=whiteboard&node-id=1-109&t=Gz2VAc87B5vFitug-4)

**Comment by KcPele** [comment]
the cutoff is because it is scrollable

**Comment by KcPele** [comment]
![Uploading Screenshot from 2024-02-22 12-25-11.png…]()

**Comment by escottalexander** [comment]
It looks less weird now that the background color is different. I am a little unsure what Jonas had in mind for what would look best. Closing for now and we will see if we get more feedback on this point.
