### ISSUE TITLE
[Task] Add the ability to view individual vectors graph lines

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/impact-calculator#38]
Prior to a recent PR that was focused on matching the design we had the ability to view each vector as its own line. This would be nice to have back.

As a bonus, look into how hard it would take to turn the individual vectors view into stacking bar graphs. This would show very clearly why a project scored as high as it did and what specific vectors contribute to their success.

This visual example is stolen from the web and should not be followed for design choices like coloring etc. 
![image](https://github.com/BuidlGuidl/impact-calculator/assets/22101475/06cc6d4b-f45b-43b0-8876-5a2e95be4fdc)
^^^ This but with the main graph line still showing. Is it possible?

**Comment by swellander** [comment]
I can take a crack at this one

**Comment by swellander** [comment]
Put up a PR for reintroducing the show/hide vector feature. Going to tackle the bar graph visualization in a separate PR
