### ISSUE TITLE
[Task] Impact vector selection menu spacing issues

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/impact-calculator#40]
1. Center the selection menu (e.g. Impact Vectors & Lists) to the right of the screen
![image](https://github.com/BuidlGuidl/impact-calculator/assets/22101475/941f3e22-bbe9-4b52-ae0c-cdf89c4cc1fa)

2. Move the “add to ballot” button of an impact vector in the selection menu slightly to the right, with the same distance to the border as the text
![image](https://github.com/BuidlGuidl/impact-calculator/assets/22101475/b6e42005-ed41-4945-989a-fdcec50210ba)

3. Move the title of an impact vector in selection menu slightly to the left to align with the impact vector description
![image](https://github.com/BuidlGuidl/impact-calculator/assets/22101475/d93201d8-8930-4108-8b21-b20baeca3912)
I bet this is because we are trimming "OSO:" but we should be trimming "OSO: " (notice the extra space at the end)

**Comment by KcPele** [comment]
> 1. Center the selection menu (e.g. Impact Vectors & Lists) to the right of the screen
>    ![image](https://private-user-images.githubusercontent.com/22101475/306472837-941f3e22-bbe9-4b52-ae0c-cdf89c4cc1fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTY0OTAsIm5iZiI6MTcwODU5NjE5MCwicGF0aCI6Ii8yMjEwMTQ3NS8zMDY0NzI4MzctOTQxZjNlMjItYmJlOS00YjUyLWFlMGMtY2RmODljNGNjMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwMDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwODlkM2Q2ZThlYzdmMDllNjNlYmFhOTU1YjA1ODcxMTJhMTM5ODQ3YTI5Y2M5YWQzOTFlYzE4OTI2YjUxMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rm25IaJAkL4viEVBtvy-_OCkm_1uSd9flHoRPcaIsxs)
> 2. Move the “add to ballot” button of an impact vector in the selection menu slightly to the right, with the same distance to the border as the text
>    ![image](https://private-user-images.githubusercontent.com/22101475/306473564-b6e42005-ed41-4945-989a-fdcec50210ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTY0OTAsIm5iZiI6MTcwODU5NjE5MCwicGF0aCI6Ii8yMjEwMTQ3NS8zMDY0NzM1NjQtYjZlNDIwMDUtZWQ0MS00OTQ1LTk4OWEtZmRjZWM1MDIxMGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwMDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNGIxMTQ4NDY5OTM1YzA3ZTA0NDA1ODBkZDZkM2Q5YzdiOWFiZTZjYmIzMDhkZDhiNzYwYjg0N2ZjZTRmMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.V2tnrUTNdnMyE7qho23-FZLpEsBGRSRzYzt4xqHsVY8)
> 3. Move the title of an impact vector in selection menu slightly to the left to align with the impact vector description
>    ![image](https://private-user-images.githubusercontent.com/22101475/306473798-d93201d8-8930-4108-8b21-b20baeca3912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTY0OTAsIm5iZiI6MTcwODU5NjE5MCwicGF0aCI6Ii8yMjEwMTQ3NS8zMDY0NzM3OTgtZDkzMjAxZDgtODkzMC00MTA4LThiMjEtYjIwYmFlY2EzOTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEwMDMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzM1ZDIxMThjYjViNDJlYjU3ZjAyY2QzZTJkNTYxZmZiMGZlNmEyZjg4OWRiYzJjYTgxODBlZDc2MWM3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rJBER1w8i4pejzehftC-3BXNGbywNy_QF0GUDmlzjfE)
>    I bet this is because we are trimming "OSO:" but we should be trimming "OSO: " (notice the extra space at the end)

for the first task,  the spacing marked with red is also on the left, so changing the one to the right will affect it

**Comment by escottalexander** [comment]
@KcPele For Item number 1, Can't we make the vector selection "stuck" to the right side and let the graph section expand to  fill that space?

**Comment by escottalexander** [comment]
Good point. We will take it as it is. Nice work!
