### ISSUE TITLE
[Task] Use real impact vectors instead of placeholders on front end

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/impact-calculator#6]
Once https://github.com/BuidlGuidl/impact-calculator/issues/4 is complete. We will likely have a set of impact vectors defined somewhere in the project. We should use those impact vectors instead of the placeholders we are currently using. When the user clicks on one of them, it will go to a page devoted to showing a graph with data exclusively for that impact vector.

**Comment by KcPele** [comment]
I will work on this
