### ISSUE TITLE
[Task] Add database

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/impact-calculator#63]
This database will eventually store the following*:
- vectors
- lists
- user state
- cached api requests
- ...
*This task is just for adding a database to the project and adding a vectors collection that is used to retrieve the active vectors instead of `packages/nextjs/components/impact-vector/ImpactVectors.ts`. No need to add any other collections

I am thinking MongoDB but only because it is familiar to me. Feel free to suggest a better storage solution if you know of one and we can discuss.

**Comment by swellander** [comment]
I have the time to take this one unless someone else wants it.

I don't have much experience with MongoDB but would love an excuse to gain some.

**Comment by swellander** [comment]
Ok I'll hop into this today
