### ISSUE TITLE
Create methods for saving a list

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/impact-calculator#73]
Add a button to the top navigation that allows a wallet connected user to save their vectors, weights and (future) filters. Try to locate a good icon but perhaps also include the text "save to lists" or something like that.

When they click the button a modal should pop up asking for a name, description... anything else that is pertinent. Help think through it and raise your hand with any other ideas or approaches if you see a better workflow.

When completed the list is saved to the database. Making these show up in the "lists" tab of the sidebar will be a different task.

**Comment by swellander** [comment]
I can take this one

**Comment by KcPele** [comment]
Gm gm. has this been implemented as it is required to complete #74

**Comment by swellander** [comment]
@KcPele still working on this, been moving pretty slowly, sorry

**Comment by swellander** [comment]
@KcPele just put up the PR
