### ISSUE TITLE
Add schemas to better handle data validation

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/impact-calculator#77]
Sam said:

> Also might be a good idea to bring in some kind of data validation to make sure all our db records stay consistent. What do y'all think? @escottalexander do you think [mongoDB schemas](https://www.mongodb.com/docs/atlas/app-services/schemas/) would be a good way to do that?

I think he is correct in thinking that a schema would be beneficial. I know you can use Mongoose for this or you can use plain Mongo to create a schema as well.

To complete this issue, create a schema for the ImpactVectors and VectorLists collections and integrate it into the existing api methods.

**Comment by swellander** [comment]
I can take this one
