### ISSUE TITLE
[Task] Build a "Create List" view

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/impact-calculator#8]
This view will be similar to the static graph view with impact vectors displayed below except that the vector weights will be adjustable (reliant on https://github.com/BuidlGuidl/impact-calculator/issues/7). The user can select impact metrics from the right sidebar and right away the graph will update with the relevant data. The user can then adjust the metrics as they want and instantly the graph will update to show how their weight changes affected the spread of projects.

**Comment by 0xChijoke** [comment]
I can work on this.
