### ISSUE TITLE
Remove graph expansion icon, instead show collapse arrow at top of impact vector selection

### ISSUE THREAD

**Issue by escottalexander** [BuidlGuidl/impact-calculator#98]
I have never liked the way that the graph expansion icon has been positioned. I think it would look and feel better if instead we had some sort of down arrow on the impact vector selection to show it can be moved out of the way. Open to discussion if you can think of a better way. 
![image](https://github.com/BuidlGuidl/impact-calculator/assets/22101475/c060df51-a404-4ee8-99b2-df6a9878e9d4)

![image](https://github.com/BuidlGuidl/impact-calculator/assets/22101475/e9b4c652-4903-4150-86f0-cea868434ac6)

**Comment by 0xChijioke** [comment]
Thanks for pointing out the issue with the graph expansion icon. I've tested your suggestion and added a down arrow to indicate the movable nature of the impact vector selection. You can see the changes in this video

https://github.com/BuidlGuidl/impact-calculator/assets/53488449/29833ae6-e3f6-4cc9-8861-28f586486e8f


Open to any further suggestions or tweaks!

**Comment by escottalexander** [comment]
Yeah, I like that. I am rethinking the icon. Maybe this one would look better? You decide. 
![image](https://github.com/BuidlGuidl/impact-calculator/assets/22101475/5a953af9-77f9-4ed3-8952-873a48298db4)
